/**
 * 生成 src/themes.generated.ts —— 把 wewrite 的 18 套排版主题（YAML）转成 TS 模块。
 *
 * 用法：
 *   node scripts/gen-themes.mjs [主题YAML目录]   # 缺省 /tmp/wewrite_themes
 *   也可用环境变量 WEWRITE_THEMES_DIR 指定
 *
 * 主题来源：github.com/imraywang/wewrite (src/wewrite/toolkit/themes/*.yaml)
 * 每套 = name + description + colors + base_css（元素级 CSS 规则）。
 * 本脚本把 base_css 解析成 selector → inline-style 映射，运行时由 markdown.ts 套用。
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { load as yamlLoad } from 'js-yaml'

const dir = process.argv[2] || process.env.WEWRITE_THEMES_DIR || '/tmp/wewrite_themes'

/** 极简 CSS 规则解析：拆 selector{decls}，按选择器存储声明串（后写覆盖先写） */
function parseCss(css) {
  const rules = {}
  const clean = css.replace(/\/\*[\s\S]*?\*\//g, '')
  const re = /([^{}]+)\{([^{}]*)\}/g
  let m
  while ((m = re.exec(clean))) {
    const selectors = m[1].split(',').map((s) => s.trim()).filter(Boolean)
    const decls = m[2]
      .split(';')
      .map((d) => d.trim())
      .filter(Boolean)
      // 过滤 WeChat 不支持的属性
      .filter((d) => !/^(max-width|min-width|margin(-inline)?)\s*:/.test(d))
      .join(';')
    for (const sel of selectors) {
      if (/[:@]/.test(sel)) continue // 跳过伪类/媒体查询残留
      if (decls) rules[sel] = decls
    }
  }
  return rules
}

const files = readdirSync(dir).filter((f) => f.endsWith('.yaml')).sort()
if (!files.length) {
  console.error(`目录 ${dir} 中没有 .yaml 主题文件`)
  process.exit(1)
}

const themes = {}
for (const f of files) {
  const raw = yamlLoad(readFileSync(join(dir, f), 'utf8'))
  if (!raw || !raw.name || !raw.base_css) {
    console.warn(`跳过无效主题文件: ${f}`)
    continue
  }
  // colors 只保留字符串值（darkmode 等嵌套对象丢弃，微信推送用浅色）
  const flatColors = {}
  for (const [k, v] of Object.entries(raw.colors || {})) {
    if (typeof v === 'string') flatColors[k] = v
  }
  themes[raw.name] = {
    name: raw.name,
    description: raw.description || '',
    colors: flatColors,
    rules: parseCss(raw.base_css),
  }
  console.log(`  ✓ ${raw.name}（${Object.keys(themes[raw.name].rules).length} 条规则）`)
}

const out = `/**
 * AUTO-GENERATED by scripts/gen-themes.mjs —— 请勿手改。
 * 来源：wewrite 18 套排版主题（github.com/imraywang/wewrite，MIT）
 * 重新生成：node scripts/gen-themes.mjs <主题YAML目录>
 */
export interface ThemeRules {
  name: string
  description: string
  colors: Record<string, string>
  /** selector -> inline style 声明串 */
  rules: Record<string, string>
}

export const WEWRITE_THEMES: Record<string, ThemeRules> = ${JSON.stringify(themes, null, 2)}

export const THEME_NAMES = Object.keys(WEWRITE_THEMES)
`

writeFileSync('src/themes.generated.ts', out)
console.log(`\n✅ 生成 src/themes.generated.ts（${Object.keys(themes).length} 套主题）`)
